#!/bin/bash

#SBATCH --mail-type=END,FAIL
#SBATCH --time=4:00:00       
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=512
#SBATCH --job-name=jobarray_ndsim
#SBATCH --array=1-1000
#SBATCH --output=jobarray_simnd.out
#SBATCH --error=jobarray_simnd.err

module load stack/2024-06 swig/4.1.1-ipvpwcc python_cuda/3.11.6 gcc/12.2.0 cmake/3.27.7
source /cluster/home/veoehl/2ptlikelihood/2ptlikelihood/bin/activate
python /cluster/home/veoehl/2ptlikelihood/xi_sim_nD.py $SLURM_ARRAY_TASK_ID