#!/bin/bash

#SBATCH --mail-type=END,FAIL
#SBATCH --time=4:00:00       
#SBATCH --cpus-per-task=16
#SBATCH --mem-per-cpu=2048
#SBATCH --job-name=jobarray_ndsim
#SBATCH --array=1-1000
#SBATCH --output=jobarray_simnd.out
#SBATCH --error=jobarray_simnd.err

module load stack/2024-06 gcc/12.2.0 swig/4.1.1-ipvpwcc python/3.11.6 cuda/12.1.1 nccl/2.18.3-1 openblas/0.3.24 python_cuda/3.11.6 cmake/3.27.7 cudnn/9.2.0
source /cluster/home/veoehl/xilikelihood/2ptlikelihood/bin/activate
export JAX_PLATFORMS=cpu
python /cluster/home/veoehl/xilikelihood/simulation_scripts/xi_sim_nD.py $SLURM_ARRAY_TASK_ID