#!/bin/bash
           
#SBATCH --ntasks=24  
#SBATCH --cpus-per-task=16      
#SBATCH --mem-per-cpu=4G      
#SBATCH --time=300:00:00
#SBATCH --output=full_sampler_n1024.out
#SBATCH --error=full_sampler_n1024.err

source load
module load openmpi/4.1.1
export JAX_PLATFORMS=cpu
source /cluster/home/veoehl/xilikelihood/likelihood-env/bin/activate
srun python /cluster/home/veoehl/xilikelihood/papers/second_paper_2025/analysis/sampler.py 1