#!/bin/bash

#SBATCH --mail-type=END,FAIL
#SBATCH --time=120:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=1024
#SBATCH --job-name=sampling_job_scale_cut_sweep
#SBATCH --array=1-6
#SBATCH --output=sampler_scale_cut_sweep.out
#SBATCH --error=sampler_scale_cut_sweep.err

module load stack/2024-06 gcc/12.2.0 swig/4.1.1-ipvpwcc python/3.11.6 cuda/12.1.1 nccl/2.18.3-1 openblas/0.3.24 python_cuda/3.11.6 cmake/3.27.7 cudnn/9.2.0
export JAX_PLATFORMS=cpu
source /cluster/home/veoehl/xilikelihood/2ptlikelihood/bin/activate
python /cluster/home/veoehl/xilikelihood/papers/second_paper_2025/analysis/sampler_scale_cut_sweep.py $SLURM_ARRAY_TASK_ID --fixed-cov
