#!/bin/bash
           
#SBATCH --ntasks=24  
#SBATCH --cpus-per-task=8     
#SBATCH --mem-per-cpu=4G      
#SBATCH --time=10:00:00
#SBATCH --output=gaussian_sampler.out
#SBATCH --error=gaussian_sampler.err
#SBATCH --mail-type=END,FAIL

source load
module load openmpi/4.1.1
export JAX_PLATFORMS=cpu
source /cluster/home/veoehl/xilikelihood/likelihood-env/bin/activate
export PYTHONPATH=/cluster/home/veoehl/xilikelihood-sampler:$PYTHONPATH
srun python /cluster/home/veoehl/xilikelihood-sampler/papers/second_paper_2025/analysis/sampler.py 7