#!/bin/bash

#SBATCH --mail-type=END,FAIL
#SBATCH --time=0:30:00       
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4096
#SBATCH --gpus=1
#SBATCH --job-name=s8_example
#SBATCH --array=8
#SBATCH --output=s8_example.out
#SBATCH --error=s8_example.err

module load stack/2024-06 swig/4.1.1-ipvpwcc python_cuda/3.11.6 gcc/12.2.0 cmake/3.27.7

source /cluster/home/veoehl/xilikelihood/venv/bin/activate
python /cluster/home/veoehl/xilikelihood/s8_example.py $SLURM_ARRAY_TASK_ID